### PR TITLE
Fix malformed require paths

### LINKED ISSUE #14: error when running on Windows
## Describe the Bug

On Windows, running `npx cytorus run` fails with the error message `Error: Can't walk dependency graph: Cannot find module ... from ...`

## Steps to Reproduce the Bug or Issue

- Prerequisite: Windows OS
- Steps to reproduce the issue
  ```
  git checkout https://github.com/NaturalIntelligence/cytorus-boilerplate.git
  npm i
  npx cytorus run
  ```

## Expected behavior

Cytorus runs without failure.

## Actual behavior

Cytorus fails and prints the error message `Error: Can't walk dependency graph: Cannot find module ... from ...`

### PR DESCRIPTION
**Pull request by actus-wirtenberger**
closes #14

### CODE REVIEW

File: src/BundledCodeBuilder.js [hunk 1]
```diff
@@ -21,11 +21,22 @@ function bundledCode(serializedFeaturePath, isCyDashboard, cliOptions){
...
 
 function requireInBrowser(moduleName){
     return "require('" + path.join( __dirname, moduleName) +"');"
 }
 
+function normalizeRequireFilePaths(fileContent) {
+    // if an OS is used that has '\' instead of '/' as path separator, then we need to
+    // replace the '\' with a '/' for the arguments of CommonJS require()
+    const backslashInRequirePathPattern = /(?<=require\(\'.*)\\(?=.*\'\))/g
+    return fileContent.replaceAll(backslashInRequirePathPattern, '/');
```
Comment (amitguptagwl) [inline src/BundledCodeBuilder.js:39]: In this code, we are replacing without checking what path separator OS supports. In my understanding, it will cause issue when using the code on Linux.

Comment (actus-wirtenberger) [reply src/BundledCodeBuilder.js:39]: Yes, you are right, thank you for pointing this out. This will cause issues when the file paths on an OS that does not use a backslash as path separator employ the backslash as an escape character. I will update the pull request with a fix.

The library is currently broken on any OS that does not use the forward slash as path separator though, since the NodeJS require() function only accepts forward slashes. To quote [the NodeJS documentation](https://nodejs.org/api/modules.html#requireid): 

> The relative paths of POSIX style are resolved in an OS independent fashion, meaning that the examples above will work on Windows in the same way they would on Unix systems.

POSIX style path implies using forward slashes in the file paths. I will update to pull request with a check which path separator the host uses before replacing.
